# Generated by Django 4.2 on 2023-12-08 12:28

import development.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("development", "0002_devrequirement_rubbing_method_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devreport",
            old_name="created_by",
            new_name="create_by",
        ),
        migrations.AddField(
            model_name="devreport",
            name="excel_path",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="devreport",
            name="pdf_path",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="devformat",
            name="format_path",
            field=models.FileField(
                blank=True,
                null=True,
                unique=True,
                upload_to=development.models.format_file_path,
            ),
        ),
    ]
