# Generated by Django 4.2 on 2023-12-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("development", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devrequirement",
            name="requirement_label",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("incharge", "Incharge"), ("coordinator", "Coordinator")],
                max_length=50,
            ),
        ),
    ]
