# Generated by Django 4.2 on 2023-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("development", "0004_alter_devreport_result_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devreport",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="devreport",
            name="dry_rubbing",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="devreport",
            name="fab_ref",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="devreport",
            name="result",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="devreport",
            name="rubbing_comment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="devreport",
            name="sample_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="devreport",
            name="style",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="devreport",
            name="tear_comment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="devreport",
            name="tensile_comment",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="devreport",
            name="wet_rubbing",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="devrequirement",
            name="dry_rubbing",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="devrequirement",
            name="tensile_warp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="devrequirement",
            name="tensile_weft",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="devrequirement",
            name="wash_tear_warp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="devrequirement",
            name="wash_tear_weft",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="devrequirement",
            name="wet_rubbing",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("incharge", "Incharge"),
                    ("coordinator", "Coordinator"),
                    ("technician", "Technician"),
                    ("merchandiser", "Merchandiser"),
                ],
                max_length=50,
            ),
        ),
    ]
