# Generated by Django 4.2 on 2023-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("development", "0004_remove_user_role_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
