# Generated by Django 4.2 on 2024-01-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devrequirement',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.buyer'),
        ),
    ]
